### ISSUE TITLE
Can't check completed on chrome

### ISSUE THREAD

**Issue by msavy** [EricWittmann/jiralist#10]
https://gist.github.com/msavy/59a9bf05cf125a47a3d7

**Comment by EricWittmann** [comment]
Interestingly it works fine for me on chrome.  But having a stack trace will hopefully help fix it even without the ability to reproduce.

@msavy - you might try refreshing everything in the settings tab to see if that helps.

**Comment by msavy** [comment]
> @msavy https://github.com/msavy - you might try refreshing everything in the settings tab to see if that helps.
> 
> Bingo!
>

**Comment by EricWittmann** [comment]
OK that helps thanks
