### ISSUE TITLE
Add column for priorities

### ISSUE THREAD

**Issue by kahboom** [EricWittmann/jiralist#11]
Add a column that shows JIRA priorities for each issue.

PR: https://github.com/EricWittmann/jiralist/pull/12

**Comment by kahboom** [comment]
@EricWittmann - Thank you for merging my PR. I just noticed that the formatting is a little off, see screenshots below. I didn't realize since I was testing with only my issues. Let me know if you'd like for me to just show the text or the icon, or if the formatting doesn't bother you at all:

My stuff:

<img width="1436" alt="screen shot 2015-10-22 at 9 43 39 am" src="https://cloud.githubusercontent.com/assets/3844502/10666751/96bbd964-78a1-11e5-8d2e-f0d4fd8745ed.png">

Everyone's stuff:

<img width="1432" alt="screen shot 2015-10-22 at 9 43 27 am" src="https://cloud.githubusercontent.com/assets/3844502/10666755/9ff76ebc-78a1-11e5-8bc1-54fc70e8ff1a.png">

**Comment by EricWittmann** [comment]
Could you add 'nowrap' to the new Priority column?  That would solve the issue I think.

**Comment by kahboom** [comment]
@EricWittmann +1 doing that now
