### ISSUE TITLE
auto refresh the issue list

### ISSUE THREAD

**Issue by brmeyer** [EricWittmann/jiralist#6]
Feel free to shoot this down, but...

Might be helpful to automatically refresh the issues list (maybe hit it once every 10 sec or so), rather than always requiring a page refresh.  Alternatively, add a refresh button?

**Comment by EricWittmann** [comment]
It already auto-refreshes:

https://github.com/EricWittmann/jiralist/blob/master/src/main/webapp/services/services.js#L184-L204

Should refresh the list every 5 minutes.  Perhaps make that configurable?  I was worried about adding even more traffic to JIRA by polling more frequently than that.

But +1 to the Refresh button.

**Comment by brmeyer** [comment]
Ah nice.  Ya, 5 minutes doesn't seem all that helpful.  The amount of bandwidth an API hit takes is probably minimal compared to the full UI, but I get the point.  Maybe something more frequent, without being harsh?  In either case, having the manual refresh button might be good.

**Comment by EricWittmann** [comment]
New version released - now has a refresh button and auto-refresh set to 30s.

**Comment by brmeyer** [comment]
You're...fast.

**Comment by EricWittmann** [comment]
Uh.  Thanks?
